export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Row = Record<string, unknown>;

type Table<RowType extends Row> = {
  Row: RowType;
  Insert: Partial<RowType> & Record<string, unknown>;
  Update: Partial<RowType> & Record<string, unknown>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      profiles: Table<{
        id: string;
        full_name: string;
        role: string;
        created_at: string;
        updated_at: string;
      }>;
      student_profiles: Table<{
        id: string;
        owner_id: string;
        first_name: string | null;
        school_college: string | null;
        stage: string;
        weekday_study_hours: number | null;
        weekend_study_hours: number | null;
        lighter_days: string[];
        tutors: string | null;
        next_assessments: string | null;
        visual_tone: string;
        onboarding_step: number;
        onboarding_completed: boolean;
        created_at: string;
        updated_at: string;
      }>;
      subjects: Table<{
        id: string;
        owner_id: string;
        name: string;
        short_name: string;
        exam_board: string | null;
        specification_code: string | null;
        specification_options: string | null;
        achieved_grade: string | null;
        target_grade: string | null;
        school_predicted_grade: string | null;
        estimated_grade: string | null;
        latest_mock_grade: string | null;
        syllabus_completion: number;
        active: boolean;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      topics: Table<{
        id: string;
        owner_id: string;
        subject_id: string;
        name: string;
        status: string;
        confidence: number | null;
        accuracy: number | null;
        error_count: number;
        last_revised: string | null;
        priority: string;
        notes: string | null;
        tutor_feedback: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      daily_plans: Table<{
        id: string;
        owner_id: string;
        plan_date: string;
        energy: number | null;
        focus: number | null;
        motivation: number | null;
        sleep_hours: number | null;
        academic_goal: string | null;
        personal_goal: string | null;
        total_focused_hours: number | null;
        evening_reflection: Json | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      daily_tasks: Table<{
        id: string;
        owner_id: string;
        daily_plan_id: string;
        subject_id: string | null;
        syllabus_topic_id: string | null;
        task: string;
        category: string;
        topic: string | null;
        starts_at: string | null;
        ends_at: string | null;
        estimated_duration: number | null;
        actual_duration: number | null;
        status: string;
        reason: string | null;
        priority_score: number | null;
        source: string | null;
        difficulty: number | null;
        confidence_before: number | null;
        confidence_after: number | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      study_sessions: Table<{
        id: string;
        owner_id: string;
        subject_id: string | null;
        topic_id: string | null;
        session_date: string;
        duration_hours: number;
        session_type: string;
        notes: string | null;
        linked_task_id: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      exams: Table<{
        id: string;
        owner_id: string;
        subject_id: string;
        paper_code: string | null;
        paper_section: string | null;
        exam_type: string;
        exam_board: string | null;
        paper: string;
        paper_year: string | null;
        completed_on: string;
        duration_minutes: number | null;
        timed: boolean;
        raw_marks: number;
        max_marks: number;
        percentage: number;
        grade: string | null;
        target_grade: string | null;
        next_boundary: number | null;
        target_boundary: number | null;
        time_remaining_minutes: number | null;
        cycle_status: string;
        notes: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      exam_errors: Table<{
        id: string;
        owner_id: string;
        exam_id: string | null;
        subject_id: string;
        topic_id: string | null;
        syllabus_topic_id: string | null;
        topic_name: string | null;
        paper_name: string | null;
        error_date: string;
        question_number: string | null;
        marks_available: number | null;
        marks_lost: number;
        category: string;
        description: string | null;
        correct_approach: string | null;
        lesson_learned: string | null;
        corrective_action: string | null;
        retest_date: string | null;
        retest_result: string | null;
        resolved: boolean;
        resolved_at: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      tutors: Table<{
        id: string;
        owner_id: string;
        name: string;
        subject_id: string | null;
        contact: string | null;
        frequency: string | null;
        lesson_duration_minutes: number | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      tutor_sessions: Table<{
        id: string;
        owner_id: string;
        tutor_id: string;
        subject_id: string | null;
        session_date: string;
        topics_covered: string | null;
        problems_identified: string | null;
        recommendations: string | null;
        homework_assigned: string | null;
        homework_completed: boolean;
        confidence_before: number | null;
        confidence_after: number | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      tutor_questions: Table<{
        id: string;
        owner_id: string;
        subject_id: string | null;
        question: string;
        status: string;
        created_at: string;
        resolved_at: string | null;
        updated_at: string;
        is_deleted: boolean;
      }>;
      goals: Table<{
        id: string;
        owner_id: string;
        timeframe: string;
        area: string;
        title: string;
        target: string | null;
        progress: number;
        status: string;
        start_date: string | null;
        target_date: string | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      journal_entries: Table<{
        id: string;
        owner_id: string;
        entry_date: string;
        sections: Json;
        tags: string[];
        publish_to_portfolio: boolean;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      projects: Table<{
        id: string;
        owner_id: string;
        title: string;
        problem: string | null;
        description: string | null;
        why_it_matters: string | null;
        technologies: string[];
        engineering_concepts: string[];
        status: string;
        started_on: string | null;
        ended_on: string | null;
        github_url: string | null;
        demo_url: string | null;
        publish_to_portfolio: boolean;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      startup_experiences: Table<{
        id: string;
        owner_id: string;
        company: string | null;
        mentor: string | null;
        starts_on: string | null;
        ends_on: string | null;
        department: string | null;
        objectives: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      startup_problems: Table<{
        id: string;
        owner_id: string;
        startup_experience_id: string;
        linked_project_id: string | null;
        problem: string;
        who_experiences_it: string | null;
        frequency: string | null;
        impact: string | null;
        existing_solution: string | null;
        possible_improvement: string | null;
        status: string;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      events: Table<{
        id: string;
        owner_id: string;
        event_name: string;
        event_date: string | null;
        venue: string | null;
        topic: string | null;
        speakers: string | null;
        people_met: string | null;
        company: string | null;
        notes: string | null;
        reflection: Json | null;
        publish_to_portfolio: boolean;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      syllabus_topics: Table<{
        id: string;
        subject_id: string;
        parent_topic_id: string | null;
        stable_code: string;
        name: string;
        specification_code: string;
        specification_ref: string;
        paper_code: string;
        paper_name: string;
        topic_level: string;
        sort_order: number;
        is_optional: boolean;
        active: boolean;
        created_at: string;
        updated_at: string;
      }>;
      topic_progress: Table<{
        id: string;
        owner_id: string;
        syllabus_topic_id: string;
        status: string;
        confidence: number | null;
        accuracy: number | null;
        priority: string;
        last_revised: string | null;
        notes: string | null;
        tutor_feedback: string | null;
        retest_date: string | null;
        tutor_flag: boolean;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      topic_diagnostics: Table<{
        id: string;
        owner_id: string;
        subject_id: string;
        syllabus_topic_id: string;
        diagnostic_date: string;
        questions_attempted: number | null;
        correct: number | null;
        marks_scored: number;
        marks_available: number;
        percentage: number;
        confidence_before: number | null;
        confidence_after: number | null;
        notes: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      mock_schedule_templates: Table<{
        id: string;
        owner_id: string;
        day_of_week: number;
        subject_id: string | null;
        paper_code: string | null;
        label: string;
        active: boolean;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      interest_profiles: Table<{
        id: string;
        owner_id: string;
        broad_interests: string[];
        free_text: string | null;
        created_at: string;
        updated_at: string;
      }>;
      course_interests: Table<{
        id: string;
        owner_id: string;
        course_name: string;
        interest_level: number;
        reason: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      student_university_choices: Table<{
        id: string;
        owner_id: string;
        university: string;
        course: string;
        entry_year: string | null;
        typical_entry_requirements: string | null;
        required_subjects: string | null;
        contextual_requirements: string | null;
        admissions_tests: string | null;
        interest_level: number;
        status: string;
        notes: string | null;
        source_url: string | null;
        last_checked: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      career_families: Table<{
        id: string;
        name: string;
        description: string | null;
        example_roles: string[];
        skills: string[];
        typical_degree_routes: string[];
        created_at: string;
        updated_at: string;
      }>;
      student_career_interests: Table<{
        id: string;
        owner_id: string;
        career_family_id: string;
        interest_level: number;
        reason: string | null;
        status: string;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      evidence_links: Table<{
        id: string;
        owner_id: string;
        source_type: string;
        source_id: string | null;
        course_interest_id: string | null;
        university_choice_id: string | null;
        career_family_id: string | null;
        skills: string[];
        ucas_category: string | null;
        reflection_strength: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      future_maps: Table<{
        id: string;
        owner_id: string;
        title: string;
        created_at: string;
        updated_at: string;
      }>;
      future_map_nodes: Table<{
        id: string;
        owner_id: string;
        future_map_id: string | null;
        node_type: string;
        label: string;
        reference_id: string | null;
        metadata: Json | null;
        position_index: number;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      future_map_edges: Table<{
        id: string;
        owner_id: string;
        future_map_id: string | null;
        from_node_id: string | null;
        to_node_id: string | null;
        reason: string | null;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      portfolio_items: Table<{
        id: string;
        owner_id: string;
        item_type: string;
        source_id: string | null;
        title: string;
        summary: string | null;
        visibility: string;
        created_at: string;
        updated_at: string;
        is_deleted: boolean;
      }>;
      activity_history: Table<{
        id: string;
        owner_id: string;
        entity_type: string;
        entity_id: string | null;
        action: string;
        field_name: string | null;
        old_value: Json | null;
        new_value: Json | null;
        metadata: Json | null;
        changed_at: string;
        changed_by: string | null;
      }>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
